name: Update Unity Version

on:
  push:
    branches:
      - main

jobs:
  update-unity-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Unity Version
      run: |
        UNITY_VERSION="1111111"

        # Update Unity version in sdkVersions.ts
        sed -i 's/unity: ".*",/unity: "'$UNITY_VERSION'",/' sdkVersions.ts

        # Commit the updated sdkVersions.ts file
        git config user.name "yuwenjian"
        git config user.email "740225978@qq.com"
        git add src/constants.js
        git commit -m "Update API version constant [skip ci]"
        git push