name: Update SDK Versions

on:
  push:
    branches:
      - main

jobs:
  update-sdk-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_PAT }}      


    - name: Run CI Script
      run: |
        # Your CI script commands here
        # For example, make the API request and extract values
        SDK_UNITY=$(curl -s https://taptap.leanapp.cn/releases/find/version | jq -r '.data[] | select(.sdkPlugName == "unity") | .version')
        SDK_IOS=$(curl -s https://taptap.leanapp.cn/releases/find/version | jq -r '.data[] | select(.sdkPlugName == "ios") | .version')
        SDK_ANDROID=$(curl -s https://taptap.leanapp.cn/releases/find/version | jq -r '.data[] | select(.sdkPlugName == "android") | .version')
        SDK_UE4=$(curl -s https://taptap.leanapp.cn/releases/find/version | jq -r '.data[] | select(.sdkPlugName == "ue4") | .version')

        # Update the SDK versions in your file
        sed -i "s/const taptapUnity = \".*\"/const taptapUnity = \"$SDK_UNITY\"/" sdkVersions.ts
        sed -i "s/const taptapIos = \".*\"/const taptapIos = \"$SDK_IOS\"/" sdkVersions.ts
        sed -i "s/const taptapAndroid = \".*\"/const taptapAndroid = \"$SDK_ANDROID\"/" sdkVersions.ts
        sed -i "s/const taptapUnreal = \".*\"/const taptapUnreal = \"$SDK_UE4\"/" sdkVersions.ts

    - name: Commit and Push Changes
      run: |
        git config --global user.email "740225978@qq.com"
        git config --global user.name "yuwenjian"
        git add -A
        git commit -m "Update SDK Versions [skip ci]"
        git push
