name: Update Constant from API

on:
  schedule:
    - cron: '4 12 * * *'

jobs:
  update-constant:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update Constant from API
      run: |
        API_URL="https://taptap.leanapp.cn/releases/find/version"
        NEW_CONSTANT_VALUE=$(curl -s $API_URL)
  
        # Assuming your constant is stored in a file like constants.js
        echo "export const API_VERSION = '$NEW_CONSTANT_VALUE';" > src/constants.js

        # Commit the updated constant file
        git config user.name "yuwenjian"
        git config user.email "740225978@qq.com"
        git add src/constants.js
        git commit -m "Update API version constant [skip ci]"
        git push
