name: Update SDK Versions

on:
  push:
    branches:
      - master

jobs:
  update-sdk-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_PAT }}      


    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update SDK Versions
      run: |
        API_URL="https://taptap.leanapp.cn/releases/find/version"
        RESPONSE=$(curl -s $API_URL)

        TAPTAP_UNITY_VERSION=$(echo $RESPONSE | jq -r '.data[] | select(.sdkPlugName == "unity") | .version')
        TAPTAP_IOS_VERSION=$(echo $RESPONSE | jq -r '.data[] | select(.sdkPlugName == "ios") | .version')
        TAPTAP_ANDROID_VERSION=$(echo $RESPONSE | jq -r '.data[] | select(.sdkPlugName == "android") | .version')
        TAPTAP_UNREAL_VERSION=$(echo $RESPONSE | jq -r '.data[] | select(.sdkPlugName == "ue4") | .version')

        # Update the variables in sdkVersions.ts file
        sed -i "s/taptapUnity: \"[^\"]*\"/taptapUnity: \"$TAPTAP_UNITY_VERSION\"/" sdkVersions.ts
        sed -i "s/taptapIos: \"[^\"]*\"/taptapIos: \"$TAPTAP_IOS_VERSION\"/" sdkVersions.ts
        sed -i "s/taptapAndroid: \"[^\"]*\"/taptapAndroid: \"$TAPTAP_ANDROID_VERSION\"/" sdkVersions.ts
        sed -i "s/taptapUnreal: \"[^\"]*\"/taptapUnreal: \"$TAPTAP_UNREAL_VERSION\"/" sdkVersions.ts
       
        git config --global user.email "740225978@qq.com"
        git config --global user.name "yuwenjian"
        git add sdkVersions.ts
        git commit -m "Update SDK Versions [skip ci]"
        git push