name: Update Unity Version

on:
  push:
    branches:
      - main

jobs:
  update-unity-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Unity Version
      run: |
        UNITY_VERSION="1111111"

        # Update Unity version in sdkVersions.ts
        sed -i 's/unity: ".*",/unity: "'$UNITY_VERSION'",/' sdkVersions.ts

        # Commit the updated sdkVersions.ts file
        git init
        git remote add https://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@github.com/yuwenjian/TestA.git HEAD:main
        # git add .
        # git commit -m "Update unity version"
        # git push
