# .github/workflows/preview-env-deploy.yml

name: Deploy Preview Environment

on:
  pull_request:
    types: [opened, synchronize]

env:
  REGION: cn-n1
  APP_ID: 1lCdsdSexAAcZAd5ide31X1s-9Nh9j0Va
  GROUP: web

jobs:
  deploy-preview-environment:
    runs-on: ubuntu-latest
    environment:
      name: preview/${{ github.head_ref }}
      url: ${{ env.PREVIEW_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Install lean-cli
        run: |
          sudo curl -L -o /bin/lean https://github.com/leancloud/lean-cli/releases/download/v1.2.3/lean-linux-x64
          sudo chmod +x /bin/lean

      - name: Deploy
        run: |
          lean login --region ${{ env.REGION }} --token ${{ secrets.ACCESS_TOKEN }}
          if [ $? -ne 0 ]; then
            echo "Lean login failed"
            exit 1
          fi
          lean switch --region ${{ env.REGION }} --group ${{ env.GROUP }} ${{ env.APP_ID }}
          PREVIEW_URL=$(lean preview deploy)
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV